version: "3.4"

services:
    web:
        build: .
        ports:
            - "8080:80"
        depends_on:
            - neo4j
    neo4j:
        image: "neo4j"
        ports:
          - "7687:7687"       
          - "7473:7473"       
          - "7474:7474"

