export const INIT_SIGNALR = 'INIT_SIGNALR';
export const INIT_API = 'INIT_API';
export const INIT_CONNECTION = 'INIT_CONNECTION';

export const REQUEST_CONTEXTS = 'REQUEST_CONTEXTS';
export const UPDATE_CONTEXTS = 'UPDATE_CONTEXTS';
export const SET_CONTEXT = 'SET_CONTEXT';


export const REQUEST_NAMESPACES = 'REQUEST_NAMESPACES';
export const UPDATE_NAMESPACES = 'UPDATE_NAMESPACES';
export const SET_NAMESPACE = 'SET_NAMESPACE';


export const REQUEST_IN_PROGRESS = 'REQUEST_IN_PROGRESS';