export const INIT_CONNECTION = 'INIT_CONNECTION';
export const REQUEST_CONTEXTS = 'REQUEST_CONTEXTS';
export const UPDATE_CONTEXTS = 'UPDATE_CONTEXTS';
export const REQUEST_NAMESPACES = 'REQUEST_NAMESPACES';
export const UPDATE_NAMESPACES = 'UPDATE_NAMESPACES';